version: '3.8'

services:
  php:
    image: infinibrium:${TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env.${ENV:-production}
    volumes:
      - storage:/var/www/html/infinibrium/storage
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      php:
        condition: service_healthy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl:/etc/ssl:ro
      - storage:/var/www/html/infinibrium/public/storage:ro
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data
    networks:
      - appnet

  horizon:
    image: infinibrium:${TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env.${ENV:-production}
    depends_on:
      - redis
      - php
    command: ["php", "artisan", "horizon"]
    volumes:
      - storage:/var/www/html/infinibrium/storage
    networks:
      - appnet

volumes:
  storage:
  redis-data:

networks:
  appnet:
    driver: bridge